apiVersion: v1
kind: ConfigMap
metadata:
  name: incident-api-config
  namespace: incident-mgmt
data:
  POSTGRES_HOST: incident-db-svc
  POSTGRES_PORT: "5432"
  POSTGRES_DB: incident_store
  LISTEN_PORT: "8200"
